// Entity representing a temporary access code generated by a patient.
package com.example_jelle.backenddico.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
public class AccessCode {
    // The unique identifier for the access code.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The unique, randomly generated code string.
    @Column(unique = true, nullable = false)
    private String code;

    // The timestamp when the code was created.
    @Column(nullable = false)
    private LocalDateTime creationTime;

    // The timestamp when the code will expire.
    @Column(nullable = false)
    private LocalDateTime expirationTime;

    // The user (patient) who generated this access code.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // Gets the ID of the access code.
    public Long getId() {
        return id;
    }

    // Sets the ID of the access code.
    public void setId(Long id) {
        this.id = id;
    }

    // Gets the access code string.
    public String getCode() {
        return code;
    }

    // Sets the access code string.
    public void setCode(String code) {
        this.code = code;
    }

    // Gets the creation time of the access code.
    public LocalDateTime getCreationTime() {
        return creationTime;
    }

    // Sets the creation time of the access code.
    public void setCreationTime(LocalDateTime creationTime) {
        this.creationTime = creationTime;
    }

    // Gets the expiration time of the access code.
    public LocalDateTime getExpirationTime() {
        return expirationTime;
    }

    // Sets the expiration time of the access code.
    public void setExpirationTime(LocalDateTime expirationTime) {
        this.expirationTime = expirationTime;
    }

    // Gets the user associated with this access code.
    public User getUser() {
        return user;
    }

    // Sets the user associated with this access code.
    public void setUser(User user) {
        this.user = user;
    }
}
